version: "3"

services:

  runtime-setup:
    image: netty:centos-6-20
    build:
      args:
        java_version : "20.0.2-zulu"

  build:
    image: netty:centos-6-20

  build-leak:
    image: netty:centos-6-20

  build-boringssl-static:
    image: netty:centos-6-20

  build-leak-boringssl-static:
    image: netty:centos-6-20

  shell:
    image: netty:centos-6-20
