# ----------------------------------------------------------------------------
# Copyright 2021 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: Deploy project

on:
  push:
    branches: [ "4.1" ]

  schedule:
    - cron: '30 1 * * 1'  # At 01:30 on Monday, every Monday.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions: read-all

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

jobs:
  stage-snapshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - setup: linux-x86_64-java8
            docker-compose-build: "-f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml build"
            docker-compose-run: "-f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml run stage-snapshot"
          - setup: linux-aarch64
            docker-compose-build: "-f docker/docker-compose.centos-7.yaml build"
            docker-compose-run: "-f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-stage-snapshot"

    name: stage-snapshot-${{ matrix.setup }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

      - uses: actions/checkout@v3

      # Cache .m2/repository
      - name: Cache local Maven repository
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.setup }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.setup }}-
            ${{ runner.os }}-maven-

      # Enable caching of Docker layers
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        env:
          docker-cache-name: staging-${{ matrix.setup }}-cache-docker
        continue-on-error: true
        with:
          key: ${{ runner.os }}-staging-${{ env.docker-cache-name }}-{hash}
          restore-keys: |
            ${{ runner.os }}-staging-${{ env.docker-cache-name }}-

      - name: Create local staging directory
        run: mkdir -p ~/local-staging

      - name: Build docker image
        run: docker-compose ${{ matrix.docker-compose-build }}

      - name: Stage snapshots to local staging directory
        run: docker-compose ${{ matrix.docker-compose-run }}

      - name: Upload local staging directory
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.setup }}-local-staging
          path: ~/local-staging
          if-no-files-found: error

  deploy-staged-snapshots:
    runs-on: ubuntu-latest
    # Wait until we have staged everything
    needs: stage-snapshot
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      # Cache .m2/repository
      - name: Cache local Maven repository
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-deploy-staged-snapshots-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-deploy-staged-snapshots-
            ${{ runner.os }}-maven-

      # Setup some env to re-use later.
      - name: Prepare environment variables
        run: |
          echo "LOCAL_STAGING_DIR=$HOME/local-staging" >> $GITHUB_ENV

      # Hardcode the staging artifacts that need to be downloaded.
      # These must match the matrix setups. There is currently no way to pull this out of the config.
      - name: Download linux-aarch64 staging directory
        uses: actions/download-artifact@v3
        with:
          name: linux-aarch64-local-staging
          path: ~/linux-aarch64-local-staging

      - name: Download linux-x86_64-java8 staging directory
        uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-java8-local-staging
          path: ~/linux-x86_64-java8-local-staging

      - name: Merge staging repositories
        run: |
          mkdir -p ~/local-staging/deferred
          cat ~/linux-aarch64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
          cp -r ~/linux-aarch64-local-staging/deferred/* ~/local-staging/deferred/
          cat ~/linux-x86_64-java8-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
          cp -r ~/linux-x86_64-java8-local-staging/deferred/* ~/local-staging/deferred/

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Deploy local staged artifacts
        run: ./mvnw -B --file pom.xml org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DaltStagingDirectory=$LOCAL_STAGING_DIR
